#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.14.3  1996/03/11  01:42:58  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:14:09  marty]
#
# Revision 1.1.14.2  1996/02/22  20:50:14  root
# 	ENDGAME: Remove building validation for IBM
# 	[1996/02/22  20:49:47  root]
# 
# Revision 1.1.14.1  1995/12/08  22:06:15  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/4  1995/05/17  15:38 UTC  mgm
# 	merge
# 
# 	HP revision /main/HPDCE02/mgm_test/1  1995/04/14  19:14 UTC  mgm
# 	build functional tests only
# 
# 	HP revision /main/HPDCE02/3  1994/10/10  13:27 UTC  mothra
# 	Merge Hpdce02_04 to HPDCE02 branch
# 	[1995/12/08  21:42:19  root]
# 
# Revision 1.1.12.8  1994/09/29  20:46:50  melman
# 	removed admin dirs
# 	[1994/09/29  16:54:43  melman]
# 
# Revision 1.1.12.7  1994/08/09  17:41:12  root
# 	Null change, just testing.
# 	[1994/08/09  17:40:57  root]
# 
# 	HP revision /main/HPDCE01/1  1994/04/06  20:30 UTC  rmm
# 
# 	HP revision /main/rmm_rodan_work/1  1994/04/06  20:22 UTC  rmm
# 
# Revision 1.1.12.6  1994/05/31  18:56:50  baum
# 	Merged with changes from 1.1.12.5
# 	[1994/05/31  18:56:43  baum]
# 
# 	Added dce branch
# 	[1994/05/31  18:52:43  baum]
# 
# Revision 1.1.12.5  1994/05/26  18:06:18  pwang
# 	Merged with changes from 1.1.12.4
# 	[1994/05/26  18:06:12  pwang]
# 
# 	Added tools to SUBDIRS
# 	[1994/05/26  18:02:16  pwang]
# 
# Revision 1.1.12.4  1994/05/26  15:59:51  tom
# 	Bug 10786 - Remove diskless tests.
# 	[1994/05/26  15:54:13  tom]
# 
# Revision 1.1.12.3  1994/05/04  21:53:00  mori_m
# 	CR 9701:  RPC runtime I18N extension functional test drop.
# 	[1994/05/04  21:06:48  mori_m]
# 
# Revision 1.1.12.2  1994/03/21  16:28:57  bhaim
# 	Fixed 10192
# 	[1994/03/21  16:28:37  bhaim]
# 
# Revision 1.1.12.1  1994/02/10  23:40:56  rousseau
# 	Added admin tree.
# 	[1994/02/10  23:40:47  rousseau]
# 
# Revision 1.1.10.6  1993/08/20  14:24:02  pellis
# 	Added ${BUILD_SYSTEST} to EXPLIB_SUBDIRS to fix missing xx_ library
# 	problem.
# 	[1993/08/20  14:23:35  pellis]
# 
# Revision 1.1.10.5  1993/08/19  20:43:22  pellis
# 	Added ${BUILD_SYSTEST} back to SUBDIRS since tests are now building
# 	ok on HP-UX and OSF/1.
# 	[1993/08/19  20:43:07  pellis]
# 
# Revision 1.1.10.4  1993/07/23  18:02:29  cmckeen
# 	Adding tet to SUBDIRS, EXPINC_SUBDIRS, and EXPLIB_SUBDIRS.
# 	[1993/07/23  18:02:00  cmckeen]
# 
# Revision 1.1.10.3  1993/07/22  17:23:57  pellis
# 	Temporarily removed systest from SUBDIRS until TETized system tests
# 	are submitted.
# 	[1993/07/22  17:23:32  pellis]
# 
# Revision 1.1.10.2  1993/05/24  20:48:18  cjd
# 	Submitting 102-dme port to 103i
# 	[1993/05/24  20:15:50  cjd]
# 
# Revision 1.1.8.2  1993/05/19  14:12:07  jd
# 	Don't run any DFS paths if NO_DFS is set.
# 	[1993/05/19  14:11:50  jd]
# 
# Revision 1.1.4.5  1992/12/31  19:10:19  pellis
# 	Corrected the spelling for ${BUILD_DISKLES}.
# 	[1992/12/31  18:24:01  pellis]
# 
# Revision 1.1.4.4  1992/12/06  03:02:39  zeliff
# 	Embedding Copyrights
# 	[1992/12/06  03:00:38  zeliff]
# 
# Revision 1.1.4.3  1992/11/04  18:18:13  root
# 	Comment out OTHERS and ILIST for the time being until the scripts are
# 	ready for release.
# 	[1992/11/04  18:15:08  root]
# 
# Revision 1.1.4.2  1992/11/02  15:32:45  root
# 	Added OTHERS and ILIST for install pass
# 	[1992/10/27  20:02:01  root]
# 
# Revision 1.1.2.8  1992/04/21  19:08:18  rps
# 	do library pass in systest (jeez!)
# 	[1992/04/21  19:05:23  rps]
# 
# Revision 1.1.2.7  1992/04/16  16:10:15  rps
# 	fix checkin typo
# 	[1992/04/16  16:08:05  rps]
# 
# Revision 1.1.2.6  1992/04/15  17:34:25  rps
# 	Add systest take 2
# 	[1992/04/15  16:10:45  rps]
# 
# Revision 1.1.2.5  1992/03/19  19:06:05  rps
# 	Undo systest -- jumped the gun
# 	[1992/03/19  19:04:02  rps]
# 
# Revision 1.1.2.4  1992/03/18  01:34:51  rps
# 	Add systest directory
# 	[1992/03/18  01:34:18  rps]
# 
# Revision 1.1.2.3  1992/02/11  16:18:17  eperkins
# 	Added NO_DFS and NO_SYSTEST build conditionals
# 	[1992/02/11  16:17:22  eperkins]
# 
# Revision 1.1.2.2  1992/02/07  19:59:38  eperkins
# 	Added NO_DFS build conditional
# 	[1992/02/07  19:58:41  eperkins]
# 
# Revision 1.1  1992/01/19  14:38:06  devrcs
# 	Initial revision
# 
# $EndLog$
#
#
#
.ifndef NO_DFS
BUILD_DFS = file
.endif

.ifndef NO_SYSTEST
BUILD_SYSTEST =  systest
.endif

.if ${TARGET_MACHINE} == "HP800"
VALIDATION_TEST = validation
.endif

.ifdef BUILD_FUNC_TESTS
DATA_SUBDIRS =   threads rpc directory security ${BUILD_DFS} functional ${VALIDATION_TEST}        
EXPINC_SUBDIRS = include threads rpc directory time security ${BUILD_DFS} tet functional
EXPLIB_SUBDIRS = lib threads rpc directory time security ${BUILD_DFS} \
                 tet functional
SUBDIRS =        include lib threads rpc directory time security tools \
		 dce ${BUILD_DFS} tet functional ${VALIDATION_TEST}
.else
EXPINC_SUBDIRS = include threads rpc directory time security \
		${BUILD_DISKLESS} ${BUILD_DFS} tet functional
DATA_SUBDIRS =   threads rpc directory security ${BUILD_DFS} functional         
EXPLIB_SUBDIRS = lib threads rpc directory time security ${BUILD_DFS} \
		${BUILD_DISKLESS} ${BUILD_SYSTEST} tet functional
SUBDIRS =        include lib threads rpc directory time security tools \
		 dce ${BUILD_DFS} ${BUILD_DISKLESS} ${BUILD_SYSTEST} tet functional \
		 ${VALIDATION_TEST}

#OTHERS = dcetest_config
#ILIST  = ${OTHERS}

dcetest_config_IDIR	= /test/etc/
dcetest_config.rm_IDIR	= /test/etc/
dcetest_config.clean_IDIR	= /test/etc/
.endif

.include <${RULES_MK}>
